config/routes.rb
Dvdverleih::Application.routes.draw do
  resources :dvds

 devise_for :users
 resources :users, :only => [:index, :show]

  root :to => "pages#home"
  match "/pages/kontakt"=>"pages#kontakt"
  match "/pages/impressum"=>"pages#impressum"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dvd-Verleih</title>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header">
<%= image_tag("banner.jpg", :alt => "Haw Erotik", :class => "round") %>
</div>

<div id="navigation">
Home &nbsp;&nbsp; Kategorien &nbsp;&nbsp; Account &nbsp;&nbsp; Abmelden         


</div>

<div id="content">
<%= yield %>
</div>

<div id="footer">
<%= link_to "Impressum" , pages_impressum_path %> <%= link_to "Kontakt" , pages_kontakt_path %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Dvdverleih</h1>
<% if user_signed_in? %>
	<% if current_user.role == "admin" %>
	<p><%= link_to "View List of Users", users_path %></p>
	<% end %>
<% end %>
<p><%= link_to "DVD-Liste", dvds_path %></p>


<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>


<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>